### ISSUE TITLE
Tutorial - Step by Step

### ISSUE THREAD

**Issue by ahmadd110** [harrypython/itsagramlive#1]
Hi dear
I'm new to Python. Can u make video tutorial (step by step) for it?
thanks

**Comment by harrypython** [comment]
1) Python and PIP installed, you can test doing 
`python3 -m pip -V`

2) Install
`pip install ItsAGramLive`

3) Create a file with:
```
from ItsAGramLive import ItsAGramLive
live = ItsAGramLive()
broadcast_id = live.create_broadcast()
live.start_broadcast(broadcast_id)
live.end_broadcast(broadcast_id)
```

4) and finally run:
`python3 live_broadcast.py -u yourInstagramUsername -p yourPassword`

5) Copy the URL and the key and be happy

**Comment by ahmadd110** [comment]
I install the Python. 
I run python3 -m pip -V and pip install ItsAGramLive.
But when I run the last command Shows the following error

C:\Users\new>from ItsAGramLive import ItsAGramLive
'from' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\new>
C:\Users\new>live = ItsAGramLive()
'live' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\new>
C:\Users\new>broadcast_id = live.create_broadcast()
'broadcast_id' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\new>
C:\Users\new>live.start_broadcast(broadcast_id)
'live.start_broadcast' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\new>
C:\Users\new>live.end_broadcast(broadcast_id)

**Comment by harrypython** [comment]
> But when I run the last command Shows the following error

They are not commands, you need to create a file

**Comment by ahmadd110** [comment]
Thanks a lot
It worked very well
Is it possible to add other features?
Such as comment management
 
and another question:  What is "-proxy user:password@ip:port"?

**Comment by harrypython** [comment]
>  Is it possible to add other features?

I hope the community help
