### ISSUE TITLE
KeyError: 'logged_in_user' when trying to login

### ISSUE THREAD

**Issue by pledi** [harrypython/itsagramlive#11]
**Description**
When trying to run `live.start() ` the program returns a KeyError: 
```
logging in...
Traceback (most recent call last):
  File "live_broadcast.py", line 5, in <module>
    live.start()
  File "/home/User/Documents/itsagramlive/ItsAGramLive/ItsAGramLive.py", line 197, in start
    if self.login():
  File "/home/User/Documents/itsagramlive/ItsAGramLive/ItsAGramLive.py", line 106, in login
    self.username_id = self.LastJson["logged_in_user"]["pk"]
KeyError: 'logged_in_user'
```

**Steps to reproduce the behavior:**
1. Checkout the latest version, at the moment 1.2.2
2. run `python3 live_broadcast.py -u yourInstagramUsername -p yourPassword `

**Expected behavior**
Logging in, asking for 2FA Code.

**Additional Information**
Instagram Account has 2FA with Google Authenticator App enabled
Already tested disabling 2FA

**Comment by harrypython** [comment]
It looks like a login error before 2FA.

Do you check your Instagram password? Are you sure there is no space at the end of the string?

**Comment by pledi** [comment]
my password included a few special characters, changed it and seems to work now, thanks
