### ISSUE TITLE
Accept, reject and close requests to join a live

### ISSUE THREAD

**Issue by jozephbrasil** [harrypython/itsagramlive#15]
Would be wonderful if the accept, reject and close requests to being part of a live is accessible via this script.

**Comment by harrypython** [comment]
I agree, would be wonderful 😁

For this we need to know the endpoint and the parameters/data needs.

**Comment by salehbjd123** [comment]
I wiil waite for this script release

**Comment by Nesslax** [comment]
it's an amazing feature if we can add it :D it would be awesome

**Comment by Nesslax** [comment]
to make the work easy for you : https://github.com/dilame/instagram-private-api/blob/master/docs/classes/_repositories_live_repository_.liverepository.md

**Comment by harrypython** [comment]
Thank you @Nesslax but there is no method to join in a live 😩

**Comment by Nesslax** [comment]
there is : /api/v1/live/${broadcastId}/get_join_request_counts/

do you think it's possible to use Wireshark to see all the requests sent by Instagram. and capture them?

**Comment by Nesslax** [comment]
here is the issue talking about it 
https://github.com/dilame/instagram-private-api/issues/1164

**Comment by harrypython** [comment]
@Nesslax 

> there is : /api/v1/live/${broadcastId}/get_join_request_counts/

This is not the right one, this request just checks if you have someone asking to join the live.

> do you think it's possible to use Wireshark to see all the requests sent by Instagram. and capture them?

Check this: https://github.com/itsMoji/Instagram_SSL_Pinning 
I use combined with an [Android Virtual Device](https://developer.android.com/studio/run/managing-avds) but it's possible to use an old device too.

**Comment by harrypython** [comment]
@Nesslax I think you right (https://github.com/dilame/instagram-private-api/issues/1164#issuecomment-723674446).

A lot of people ask for this enhancement, I don't believe it's achievable.
