### ISSUE TITLE
share to IGTV

### ISSUE THREAD

**Issue by zittox** [harrypython/itsagramlive#17]
Do u think the option "share to IGTV" can be placed too in the end of the transmission after we type stop?

as in >>>  "To share a replay of your live video, tap Share to IGTV at the bottom of the screen after you've ended your live video and follow the on-screen instructions"
from >>  https://help.instagram.com/562982737951475

thanks , the script is amazing and stable!

**Comment by harrypython** [comment]
I'm happy to know the script make some people happy 😄 

Check my answer here #16
