### ISSUE TITLE
Web Version

### ISSUE THREAD

**Issue by RaihanStark** [harrypython/itsagramlive#18]
**Is your feature request related to a problem? Please describe.**
to some people especially non-tech users, it can be hard installing and operating the python script on their machines.

**Describe the solution you'd like**
I have a plan to make a web version of it with Django Framework, so all users can operate it with just a click and hosted it on somewhere else without need to type a certain command on their terminal every time they want to live ig.

**Additional context**
It's the same like yellowduck.tv but opensource and built with python.

**I need your suggestions**
I need your suggestion to make the project possible. like how will the login functionality works on web? are we gonna use requests? or instagram client login like yellowduck.tv? 

Thank You

**Comment by harrypython** [comment]
What about a desktop service? yellowduck.tv use a desktop app.

**Comment by RaihanStark** [comment]
We obviously will reach that point, but we need to create a web app first and then we can convert it to desktop apps using Electron.

**Comment by harrypython** [comment]
I didn't understand the need for the web app 😕 .
Is it necessary for Electron?
I have no experience in desktop apps.

**Comment by RaihanStark** [comment]
Okay, I will fork this repository and I will build the web apps from it😊

**Comment by harrypython** [comment]
I'll follow your project and please let me know if I can help with something, I'll love to 😃

**Comment by RaihanStark** [comment]
Hi harrypython.

I have created a web version of it, you can check it out (https://github.com/RaihanStark/instaliveweb) (dev release). But, I have some major problems from the API.

**Comment by RaihanStark** [comment]
Hi, Harrypython.

I have created a web version of it, you can check it out (https://github.com/RaihanStark/instaliveweb) (dev release). But, I have some major problems from the API. 

#### Case
I'm trying to store the object session after the user logged in, so I can send more requests without needing to log in again every time I send a request, to avoid the rate-limiting.

#### The Problem
After I deserialize the object and try to send any request, the servers response error 403 with the message "You've been logged out".

###### Object Serialize with pickle
```python
from ItsAGramLive import ItsAGramLive

Live = ItsAGramLive(username='foo',password='bar')
Live.login() 

f = open("pickle_data", "wb")
pickle.dump(Live, f)
f.close()
```

###### Object Deserialize 
```python
import pickle
from ItsAGramLive import ItsAGramLive

# get the object with pickle
f = open("pickle_data", "rb")
Live = pickle.load(f) # <ItsAGramLive.ItsAGramLive.ItsAGramLive object at 0x0339FD00>

Live.create_broadcast() # * ERROR(403): login_required
```

#### Solutions?
It would be great if we get and store the auth cookies and load cookies as needed and maybe adding a new function like load_session() and save_session() or something similar.

#### References
> https://instagram-private-api.readthedocs.io/en/latest/usage.html#avoiding-re-login
> https://github.com/ping/instagram_private_api/blob/master/examples/savesettings_logincallback.py


I really need your help to make this project possible. 😊

**Comment by RaihanStark** [comment]
I have a pull request #20 to solving the problems I addressed.

> p.s: I have a lot of ideas to be included in this project, I want to create documentation, testing, and more. Are you still maintaining this project?

**Comment by RaihanStark** [comment]
I assume this project is not maintained and I don't want to disturb the stability of this project, and I make a new one, please check it out: https://github.com/RaihanStark/instalivecli
