### ISSUE TITLE
OBS Studio native integration

### ISSUE THREAD

**Issue by ASchneiderBR** [harrypython/itsagramlive#21]
**Describe the solution you'd like**
It would be great since OBS Studio is used by thousands of people and it is also written in Python, to have a native integration with your tool. Maybe a dock window with username and password fields so we can populate with our Instagram credentials and automatically start the live stream. Since I plan to use multiple Instagram accounts to stream to, would be nice to be able to copy the current RTMP URL and key so we can start streaming using [obs-multi-rtmp](https://github.com/sorayuki/obs-multi-rtmp) for example. Also would be great to have checkbox for chat commands and another textbox to send a command. Not sure if it possible to read real-time conversations for the current stream. That would be the ultimate OBS to Instagram solution in my opinion, there is nothing else available at the moment.

Thanks for your great work here @harrypython, I really appreciate what you've done here. Have a great day!

**Comment by harrypython** [comment]
Hi @tatunts 

> Maybe a dock window with username and password fields so we can populate with our Instagram credentials and automatically start the live stream.

Check what nice project @RaihanStark is doing https://github.com/RaihanStark/instalivecli

> Since I plan to use multiple Instagram accounts to stream to, would be nice to be able to copy the current RTMP URL and key so we can start streaming using [obs-multi-rtmp](https://github.com/sorayuki/obs-multi-rtmp) for example.

When you created streaming using itsagramlive the RTMP key is copied to clipboard. It's that you talk about?

> Also would be great to have checkbox for chat commands and another textbox to send a command. Not sure if it possible to read real-time conversations for the current stream.

I try some times but there's a parameter to do this relative with the device, what I recommend is open the live in a browser and interact there.

Also, looks like your suggestion can use the obs-websocket to remote control the OBS.

For now, I'm kind of busy with other projects but I'll stay here trying to help the community.

**Comment by ASchneiderBR** [comment]
> Hi @tatunts
> 
> > Maybe a dock window with username and password fields so we can populate with our Instagram credentials and automatically start the live stream.
> 
> Check what nice project @RaihanStark is doing https://github.com/RaihanStark/instalivecli
> 
> > Since I plan to use multiple Instagram accounts to stream to, would be nice to be able to copy the current RTMP URL and key so we can start streaming using [obs-multi-rtmp](https://github.com/sorayuki/obs-multi-rtmp) for example.
> 
> When you created streaming using itsagramlive the RTMP key is copied to clipboard. It's that you talk about?
> 
> > Also would be great to have checkbox for chat commands and another textbox to send a command. Not sure if it possible to read real-time conversations for the current stream.
> 
> I try some times but there's a parameter to do this relative with the device, what I recommend is open the live in a browser and interact there.
> 
> Also, looks like your suggestion can use the obs-websocket to remote control the OBS.
> 
> For now, I'm kind of busy with other projects but I'll stay here trying to help the community.

Thanks a lot! I'll take a look at @RaihanStark project.

Have a great week mate!
