### ISSUE TITLE
join on live with request

### ISSUE THREAD

**Issue by salehbjd123** [harrypython/itsagramlive#22]
hi harry please add new script about accept request to join on live

**Comment by harrypython** [comment]
Duplicate => #15

**Comment by salehbjd123** [comment]
I can’t understand your reply
Can u explain me how can i do this script?

Sent from my iPhone

On Aug 10, 2020, at 05:46, Harry Python <notifications@github.com> wrote:

﻿

Duplicate => #15<https://github.com/harrypython/itsagramlive/issues/15>

**Comment by harrypython** [comment]
Your request it's the same in the #15 
It's not possible now join a live by the script
