### ISSUE TITLE
comments mute not work

### ISSUE THREAD

**Issue by mrb0098** [harrypython/itsagramlive#23]
Hi
First of all, thank you very much for this module
but i try to use this function : `live.mute_comments()` but its not work
may be instagram changed some thing
please help me .
Environment :‍
python 3.7
ubuntu server 18.04 lts

**Comment by harrypython** [comment]
Hi @mrb0098,

I just test and it's working for me.

Do you have any output message? Did other commands work?

**Comment by mrb0098** [comment]
yes other functions like `live.stop()` is work for me
i commented the` while self.is_running:` line 244 because i use ffmpeg command after `live.play` ( use stream_server + stream_key for live streaming) after ffmpeg command i use `live.mute_comments()` but its not work :(

**Comment by harrypython** [comment]
Can you share your code, please?
