### ISSUE TITLE
Syntax error?

### ISSUE THREAD

**Issue by regstuff** [harrypython/itsagramlive#24]
Hi
When I run live_broadcast.py, I get the following error
```
File "path/to/ItsAGramLive.py", line 18
    previewWidth: int = 1080
                ^
SyntaxError: invalid syntax
```

My live_broadcast.py consists of 
```
from ItsAGramLive import ItsAGramLive

live = ItsAGramLive(
  username='username',
  password='pass'
)

live.start()
```
Python version is 3.5.2
I'm using Windows 10
Any pointers on what I'm doing wrong?
Thanks

**Comment by harrypython** [comment]
Update your Python, required is 3.6, but I recommend Python 3.7
