### ISSUE TITLE
Problem saving replay to story

### ISSUE THREAD

**Issue by gotagautier** [harrypython/itsagramlive#25]
I use Itsagramlive for about 5 months now and work perfectly until a couple weeks ago.
Now when I finish a live (I use OBS) I type STOP in the command and then press the Y key to save the replay to story, but the CMD show me the following error:

* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
....
...
..
(It follow with the same error every 60sec)

When I press ctrl + C (to stop the script) it say the following lines:

Traceback (most recent call last):
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 183, in send_request
    self.LastJson = json.loads(self.LastResponse.text)
  File "c:\Python3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "c:\Python3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python3\IG\valparaisoprofundo.py", line 11, in <module>
    live.start()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 248, in start
    self.stop()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 425, in stop
    self.add_to_post_live()
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 407, in add_to_post_live
    if self.send_request(endpoint='live/{}/add_to_post_live/'.format(self.broadcast_id),
  File "c:\Python3\lib\site-packages\ItsAGramLive\ItsAGramLive.py", line 188, in send_request
    time.sleep(60)
KeyboardInterrupt
^C

Theres any fix to this? It start happens a couple weeks ago 
I use an HP ProBook 640 G2 (i7 6600U / 12GB RAM DDR4 1333MHz / integrated graphics / Samsung EVO750 SSD) with the latest version of OBS and python3

**Comment by harrypython** [comment]
Looks like Instagram remove the feature share a live video to stories.

The error is a 404 (not found) when the script tries to save on stories.

I'll wait for a couple of weeks to confirm if it's really this problem.

**Comment by gotagautier** [comment]
> Looks like Instagram remove the feature share a live video to stories.
> 
> The error is a 404 (not found) when the script tries to save on stories.
> 
> I'll wait for a couple of weeks to confirm if it's really this problem.

Thanks! I really appreciate your work. I work with an ONG doing free interviews and concerts to instagram so its really useful

**Comment by edusachs** [comment]
> Looks like Instagram remove the feature share a live video to stories.
> 
> The error is a 404 (not found) when the script tries to save on stories.
> 
> I'll wait for a couple of weeks to confirm if it's really this problem.

Hi... many people have the same problem, in other implementations and softwares.

The Instagram disabled the feature for save Lives in stories.

Now, is different... You need to save the Lives in a video of IGTV.

Look at this thread: https://github.com/dilame/instagram-private-api/issues/1304

Can you fix your software for save the Lives in IGTV?

Thanks

**Comment by harrypython** [comment]
New version guys!

Thank you for the help @edusachs 

@gotagautier please, let me know if it's working.
