### ISSUE TITLE
Can't Bypass "challenge mode" for Account Verification

### ISSUE THREAD

**Issue by shelomito12** [harrypython/itsagramlive#27]
Today I was trying some tests but then I was presented by the following prompt:
```
$ python3.6 live_broadcast.py
Let's do it!
Choose a challenge mode (0 - SMS, 1 - Email):
```
My Instagram account from my PC (web browser) displayed the following:
![image](https://user-images.githubusercontent.com/10729787/99009980-131bda00-2517-11eb-97df-7b8d10541cad.png)

Got the code via email:
![image](https://user-images.githubusercontent.com/10729787/99010113-55ddb200-2517-11eb-842d-707b4a11462b.png)

**I was able to paste the code received by both SMS and email but now every time I want to use itsagramlive tool, it keeps displaying the same challenge prompt (like forever). I can't bypass it!**

Below is the itsagramlive script I use:
```
from ItsAGramLive import ItsAGramLive

# live = ItsAGramLive()

live = ItsAGramLive(
    username='foo',
    password='bar'
)

live.start()
```

**Comment by shelomito12** [comment]
Same issue from Yellow Duck:
![image](https://user-images.githubusercontent.com/10729787/99020073-c42c6f80-252b-11eb-8901-28968fff4c31.png)

**Comment by shelomito12** [comment]
Most likely this(?): https://www.express.co.uk/life-style/science-technology/1215962/Instagram-Down-Timeline-Unable-To-Load-iPhone-Android-App

**Comment by harrypython** [comment]
When you login a lot, Instagram will skip you and it's normal. Try this:

1. Logout from all devices
1.1 Open your account on a device (android/ios);
1.1 On Settings -> Security -> Login Activity -> Here log out all devices
1. Clean up your Python virtual environment;
1.1 delete and recreate the virtual environment
1. and change your Instagram password

**Comment by shelomito12** [comment]
Hey @harrypython, did what you suggested but now I'm being prompted with the following:

```
$ python3.6 live_broadcast.py                        
Let's do it!
/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'i.instagram.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
/home/ubuntu/.local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'i.instagram.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
```

Then I installed 2 other pip modules as suggested here: https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl

```
pip3 install certifi
pip3 install urllib3[secure]
pip3 install requests
```

But still getting the above `Unverified HTTPS request` error

**Comment by harrypython** [comment]
Can you give me some details about your environment like
What Ubuntu you are running?
Where: VM? PC? Cloud?

**Comment by shelomito12** [comment]
Ubuntu server 18.04 (headless/no gui) VM on Cloud.

```
Linux myserver 5.0.0-1014-oracle #19-Ubuntu SMP Tue Mar 17 04:50:21 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shelomito12** [comment]
Any thoughts?

**Comment by harrypython** [comment]
Can you share your live_broadcast.py?

**Comment by shelomito12** [comment]
```
from ItsAGramLive import ItsAGramLive

#live = ItsAGramLive()

# or if you want to pre-define the username and password without args
live = ItsAGramLive(
    username='ig123',
    password='hackm3'
 )

live.start()
```

**Comment by harrypython** [comment]
I have not been able to reproduce your error.
On a vagrant w / ubuntu-18.04 I needed only 3 commands to get the script to run:

```shell
sudo apt-get update
sudo apt install python3-pip
pip3 install ItsAGramLive
```

and done. My guess is that you may need to start over in a "clean" environment, sorry.
