### ISSUE TITLE
Possible to use multiple instances of ItsAGram from same IP/machine?

### ISSUE THREAD

**Issue by shelomito12** [harrypython/itsagramlive#29]
I have 2 bash scripts. One gets the IG stream key from ItsAGram and then passes the key to ffmpeg to start streaming to IG, the other script monitors until the ffmpeg process ends and then automatically input ItsAGram commands to stop and save to IGTV... Of course, all this running on the same machine.

Now, my question is: Is it possible to use more than 2 instances of ItsAGram (2+ different IG logins) from the same machine/IP? Would ItsAGram let me do that? Would be there a suspicious activity detected by IG?

**Comment by harrypython** [comment]
> Is it possible to use more than 2 instances of ItsAGram (2+ different IG logins) from the same machine/IP? Would ItsAGram let me do that? 

I can't imagine any problem with having multiple instances of ItsAGramLive running.

> Would be there a suspicious activity detected by IG?

Not using the official client to access any IG content will **always** be a risk.

Imagine that two or three people are using the same wi-fi network to transmit from different cell phones. I don't see a problem, but maybe Zuckerberg doesn't think the same way.
