### ISSUE TITLE
Two factor authentication

### ISSUE THREAD

**Issue by mkkyah** [harrypython/itsagramlive#3]
Hi,
Thank you for your code.
is it possible to add two factor authentication to itsagramlive.
It's maybe easy for personal ig account to turn it off and continue, but for a shared account with two factor authentication I'm stuck.

**Comment by harrypython** [comment]
All the authentication code is from [LevPasha/Instagram-API-python](https://github.com/LevPasha/Instagram-API-python) and looks like they had the support to 2FA.

What kind of 2FA are you using? Text message or Authentication App?

**Comment by mkkyah** [comment]
Text message

⁣Sent from TypeApp ​

**Comment by harrypython** [comment]
Can you send your code and output?

**Comment by mkkyah** [comment]
> Can you send your code and output?

sorry, which code and output?
do you mean the output which comes when trying to start broadcast with 2FA account?

**Comment by harrypython** [comment]
>  do you mean the output which comes when trying to start broadcast with 2FA account?

Yes, and how you trying to create the live

**Comment by mkkyah** [comment]
this is with usename/password only:
```
python3 live_broadcast.py -u username -p password -share True
Request return 405 error!
{'message': '', 'status': 'fail'}
Request return 404 error!
Login success!

Server: rtmps://live-upload.instagram.com:443/rtmp/
Stream Key (copied to clipboard): xxxxx....xxxx
CTRL+C to quit.
 - -^C
Ending Broadcasting
```

this is with 2FA:
```
python3 live_broadcast.py -u username -p password -share True
Request return 400 error!
{'message': '', 'two_factor_required': True, 'two_factor_info': {'username': 'username', 'sms_two_factor_on': True, 'totp_two_factor_on': False, 'obfuscated_phone_number': 'xxxx', 'two_factor_identifier': 'xxxxxxxx', 'show_messenger_code_option': False, 'show_new_login_screen': True, 'show_trusted_device_option': False, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}}, 'phone_verification_settings': {'max_sms_count': 2, 'resend_sms_delay_sec': 60, 'robocall_count_down_time_sec': 30, 'robocall_after_max_sms': True}, 'status': 'fail'}
Traceback (most recent call last):
  File "live_broadcast.py", line 7, in <module>
    live.start_broadcast(broadcast_id)
  File "/home/xxx/Downloads/itsagramlive-master/ItsAGramLive/ItsAGramLive.py", line 67, in start_broadcast
    '_uid': self.ig.username_id,
AttributeError: 'InstagramAPI' object has no attribute 'username_id'


````

**Comment by harrypython** [comment]
After some (a lot?) of test the solution I found is:
1) desactive the two factor
2) log normally
3) active the two factor again

Please let me know if this work for you.

**Comment by mkkyah** [comment]
Hi,
You mean it's not possible or easy to integrate 2FA?
The code is really working well for my account, so disabling/enabling is not a big deal for me.
But there is an account which we use a group of people as admins, when I disable/enable 2FA for that account every users device loses registration and needs new registration sms again.
Thanks anyway for looking.

**Comment by mkkyah** [comment]
One more question,
when you activate 2FA, instagram sends also single use pre-defined codes for later use. Is it possible to use them in the code for 2FA login?

**Comment by harrypython** [comment]
Hey @mkkyah , update to 0.2 and try again the 2FA by SMS.
I did a lot of changes last night 😄

**Comment by mkkyah** [comment]
@harrypython It's working and working really well. Although I didn't understand how it's authenticating, its directly connecting with success. Nothing asked, no sms.

**Comment by harrypython** [comment]
> I didn't understand how it's authenticating

After logging in for the first time Instagram registers the script as a trusted "device" and will no longer require 2FA until you change your password.

> Nothing asked, no sms.

The 0.2 version now support 2FA by SMS.

I still need some help with 2FA by TOTP.

**Comment by mkkyah** [comment]
Hi again,
I'm testing the 2FA with another ig account, it's asking a sms code, but asking it every time. Not registering the script as trusted for that account.
my other account is trusted and weirdly deactivating/activating 2FA is not changing that trusted device situation.
