### ISSUE TITLE
Two Factor Authentication not wotking

### ISSUE THREAD

**Issue by alirezab213** [harrypython/itsagramlive#32]
Dear All ,
Two Factor Authentication not working , Disconnect when the code is entered .

**Comment by harrypython** [comment]
Please, use the issue template for bugs so I can have the basic information I need.

**Comment by GitNees** [comment]
Well, I dont know what to give, thats my problem, it gave what I just gave you, i press enter after the command and it just gives me LETS DO THIS.

Is there a way to activate a better debug output?

**Comment by GitNees** [comment]
I just tested by disabling Two Factor, but still getting only LETS DO THIS! and then i get the prompt back. Did something go bad with the install? Not my first python app I use, normally with the debug output I can fiture things out, but its not giving me anything except that....

**Comment by harrypython** [comment]
Don't take me wrong but, I can't help you if I can't reproduce the error and to reproduce the error I need information.

> Well, I dont know what to give

Check the issues templates questions.

Python version? 
If you are using the itsagramlive last version? 
Are you using an environment? 
With packages installed?

> Is there a way to activate a better debug output?

You can clone the project and run it in your favourite IDE.
