### ISSUE TITLE
Live To IGTV error

### ISSUE THREAD

**Issue by omouren** [harrypython/itsagramlive#33]
Hello,
Does the live to IGTV works with your script?
I'm facing issue trying to do this with a javascript library (https://github.com/dilame/instagram-private-api/pull/1194), I have a 500 error when I post the live to IGTV.
I compared the requests that the javascript lib has and yours and it looks like the same. I'm thinking that Instagram changed something in their API recently and I wanted to verify it with an other script like yours, but I'm not familiar with python scripts, I tried to use your script but I did not succeed...

**Comment by harrypython** [comment]
I'm not sure if I understand your problem but, I believe its solved
Please check the follow issues: #25 #16 #17

**Comment by omouren** [comment]
Sorry @harrypython. I'm just asking if you can tell me if your "share live to IGTV" function is actually working with your library?
Because I'm using a library like yours, but written in Javascript, and when I save a live to IGTV, I got a 500 error from the Instagram API and I can't find why.

**Comment by harrypython** [comment]
> I'm just asking if you can tell me if your "share live to IGTV" function is actually working with your library?

Yes 🙂

**Comment by omouren** [comment]
> > I'm just asking if you can tell me if your "share live to IGTV" function is actually working with your library?
> 
> Yes 🙂

Thank you! So if it works with you, it's not an issue from Instagram, I'm going to retry this endpoint and compare (again) the API requests with yours.
