### ISSUE TITLE
Does it work with Two Factor activated?

### ISSUE THREAD

**Issue by GitNees** [harrypython/itsagramlive#35]
**Describe the bug**
Could it be that it doesnt work when Two Factor is activated?

It always says Let's Do It! but nothing else.

Not sure what else I can say.
But I get no error, just the Let's Do It!, but no keys...

**Comment by harrypython** [comment]
Looks like the two-factor authentication it's working for me, please follow the instructions in the issue template to give me more details.

Duplicate #32
