### ISSUE TITLE
Let's Do It output with or even without user and pass... No checks?

### ISSUE THREAD

**Issue by GitNees** [harrypython/itsagramlive#36]
**Describe the bug**
Let's Do It!

**To Reproduce**
Just start the command with or without user/password... It just outputs Let's Do It and no error. Just goes back to prompt.

**Expected behavior**
give more info? RTPM output?
Even disabled firewall completely

**Environment (please complete the following information):**
 - OS:win10
 - Python version: Python 3.7.4

**Settings (please complete the following information):**
 - [ ] Are you using proxy? Nope
 - [ ] Are you using two-factor authentication by text message (SMS)? Disabled it as test, same result

**Additional context**
Nope, Hope  a debug flag can help...

**Comment by harrypython** [comment]
Are you using a python virtual environment?
Can you please give me the output 
`pip3.7 list`

**Comment by GitNees** [comment]
No, no VM, just windows prompt

Here you go:

Package                  Version
------------------------ ---------
-nstapy                  0.6.0
adbutils                 0.8.2
apkutils2                1.0.0
asn1crypto               0.24.0
atomicwrites             1.4.0
beautifulsoup4           4.9.1
boltons                  20.2.1
cached-property          1.5.2
certifi                  2019.6.16
cffi                     1.12.2
chardet                  3.0.4
cigam                    0.0.3
clarifai                 2.6.2
colorama                 0.3.7
configparser             3.5.0
croniter                 0.3.36
cryptography             2.6.1
cycler                   0.10.0
Cython                   0.29.21
decorator                4.4.2
Deprecated               1.2.10
deprecation              2.1.0
docopt                   0.6.2
EasyProcess              0.2.3
emoji                    0.5.2
future                   0.17.1
googleapis-common-protos 1.6.0
grpcio                   1.21.1
html5lib                 1.1
idna                     2.8
insomniac                3.2.0
instagram-py             0.0.1
instapy                  0.6.2
instapy-chromedriver     2.46
ItsAGramLive             1.4.1
jsonschema               2.6.0
kiwisolver               1.3.1
logzero                  1.5.0
lxml                     4.5.2
matplotlib               3.3.3
MeaningCloud-python      1.1.1
natsort                  7.0.1
numpy                    1.19.3
packaging                20.4
pendulum                 2.1.2
Pillow                   8.0.1
pip                      20.3.3
plyer                    1.4.0
progress                 1.5
protobuf                 3.8.0
py                       1.9.0
pycparser                2.19
pyelftools               0.26
Pympler                  0.5
pyOpenSSL                19.0.0
pyparsing                2.4.7
pyperclip                1.8.1
PySimpleGUI              4.32.1
PySocks                  1.7.1
python-dateutil          2.8.1
pytzdata                 2020.1
PyVirtualDisplay         0.2.1
PyYAML                   5.1.1
regex                    2019.3.12
requests                 2.25.1
retry                    0.9.2
schedule                 0.5.0
selenium                 3.141.0
setuptools               40.8.0
six                      1.12.0
soupsieve                1.9.2
sourcedefender           5.0.20
TgCrypto                 1.2.0
tqdm                     4.33.0
uiautomator              0.3.6
uiautomator2             2.11.2
urllib3                  1.25.3
webdriverdownloader      1.0.0.1
webencodings             0.5.1
whichcraft               0.6.1
wrapt                    1.12.1
xmltodict                0.12.0

**Comment by harrypython** [comment]
I think I managed to reproduce your error (or found a new one) Please, try to input your password between quotes like:

`python3 live_broadcast.py -u "yourInstagramUsername" -p "yourPassword" `

**Comment by GitNees** [comment]
OMG I found it. 

I saw this in the readme: 

`from ItsAGramLive import ItsAGramLive

live = ItsAGramLive()

'# or if you want to pre-define the username and password without args
'# live = ItsAGramLive(
'#    username='foo',
'#    password='bar'
'# )

live.start()`

(had to add those ' else it would put it in bold)

So thought be default you commented the part where you fill in your username and pass by default.

But now I opened the file and saw it was uncommented. So it tried to login every time with foo and bar.

Might be good to give a check where the user or password is wrong or something like that :)

but now it works when i commented those parts except live = ItsAGramLive() and live.start()

**Comment by GitNees** [comment]
ok not sure why, bit it puts it in bold... tried to add it in code

**Comment by GitNees** [comment]
Well, got it to work
But after stopping, i get this;

* Save Live replay to IGTV ? <y/n>
command> n
* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* Except on SendRequest (wait 60 sec and resend): Expecting value: line 1 column 1 (char 0)
* 
but tried again 60secs later and still shows same except 3 times now?

I do see on my phone that the stream has ended.

Edit: Ctrl-C is only way to kill it
