### ISSUE TITLE
Pin message? (question)

### ISSUE THREAD

**Issue by GitNees** [harrypython/itsagramlive#38]
Thx for fixing the problems so quickly!

Not sure how you set labels as this is question and not a problem :)

When you stream live with your phone, you can pin messages, this would be very handy if this was also possible with trough command? or is this a limitation in the way streaming is done here?

**Comment by harrypython** [comment]
Looks like a nice new feature for a future version. I will considerate.

**Comment by harrypython** [comment]
Hey, @GitNees can you update to 1.5.5 and test this new feature?
Thanks.

**Comment by GitNees** [comment]
@harrypython Very nice, but you still need to update the command list after you press enter. it's missing the pin and unpin command, but since I saw the code, knew it was pin :)
Didn't test the Unpin, but Pin worked!
Will test another stream tomorrow. Thx for the quick add of the feature!

**Comment by harrypython** [comment]
I'm assuming it's working

**Comment by GitNees** [comment]
Oh Sorry hadnt had an occasion to test the other part, but if I use it next time, will test it again and report back if it doesnt :)
