### ISSUE TITLE
Fullscreen live

### ISSUE THREAD

**Issue by karakolaaa** [harrypython/itsagramlive#41]
Hello, thanks for the script, it's very usefull :)

It's normal the live appears cropped and not fullscreen like a normal live from the app?

How can do it fullscreen?

**Comment by harrypython** [comment]
Are you using OBS?
If yes, adjust the output video to a ratio of 9:16.

**Comment by karakolaaa** [comment]
Thank you very much for the quick reply Harry, you are the best!

Solved ;)
