### ISSUE TITLE
Turn comments off

### ISSUE THREAD

**Issue by mkkyah** [harrypython/itsagramlive#5]
Hi,
How can we turn off the comments in the code?

**Comment by harrypython** [comment]
Can be a new feature.

I believe that the endpoints for this are:
live/{broadcast-id}/mute_comment/
live/{broadcast-id}/unmute_comment/

**Comment by mkkyah** [comment]
Hi, I'm testing new features. Mute comments is working but I'm not sure about send notifications

**Comment by harrypython** [comment]
> Mute comments is working

Great!

>but I'm not sure about send notifications

Yes, the same here, sometimes works, sometimes not, I think it's something on the instagram app
