### ISSUE TITLE
ffmpeg 3.3.0 (-deinterlace) command used in live_broadcast_ffmpeg.py is too old

### ISSUE THREAD

**Issue by bugbounted** [harrypython/itsagramlive#56]
Hi [Harry Python](https://github.com/harrypython),
you used -deinterlace in your ffmpeg command exist in live_broadcast_ffmpeg.py.
I'm trying to deploy it on heroku but heroku used amd64 static builds ubuntu & ffmpeg 3.3.0 doesn't have this build.
please update your ffmpeg command & use yadif insteed of deinterlace , because it's not work on any ffmpeg static builds.
https://www.johnvansickle.com/ffmpeg/old-releases/
you can see in above link , oldest version of ffmpeg amd64 static build is [ffmpeg-4.1.4-amd64-static.tar.xz](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.1.4-amd64-static.tar.xz) & deinterlace dead line in 3.3.0 or higher versions.
waiting for your response
finest regards

**Comment by dedshit** [comment]
> Hi [Harry Python](https://github.com/harrypython),
> you used -deinterlace in your ffmpeg command exist in live_broadcast_ffmpeg.py.
> I'm trying to deploy it on heroku but heroku used amd64 static builds ubuntu & ffmpeg 3.3.0 doesn't have this build.
> please update your ffmpeg command & use yadif insteed of deinterlace , because it's not work on any ffmpeg static builds.
> https://www.johnvansickle.com/ffmpeg/old-releases/
> you can see in above link , oldest version of ffmpeg amd64 static build is [ffmpeg-4.1.4-amd64-static.tar.xz](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.1.4-amd64-static.tar.xz) & deinterlace dead line in 3.3.0 or higher versions.
> waiting for your response
> finest regards

heroku now suspending accounts using ffmpeg for restreaming
