### ISSUE TITLE
View comments

### ISSUE THREAD

**Issue by angeloruggieridj** [harrypython/itsagramlive#8]
Hi, I really like your project and, if you want I could help you to extend this project!

I've created a function to get the comments of a Live.
The code is shown below:

```
    def get_comments(self):
        if self.send_request("live/{}/get_comment/".format(self.broadcast_id)):
            for comment in self.LastJson['comments']:
                print(f"{comment['user']['username']} has posted a new comment: {comment['text']}")
```

**Comment by harrypython** [comment]
Thank you so much,
Please, use the Feature request model (when you open a new issue) and fell free to do a pull request 😃

**Comment by angeloruggieridj** [comment]
How could I do to pull request?

**Comment by ahmadd110** [comment]
> Hi, I really like your project and, if you want I could help you to extend this project!
> 
> I've created a function to get the comments of a Live.
> The code is shown below:
> 
> ```
>     def get_comments(self):
>         if self.send_request("live/{}/get_comment/".format(self.broadcast_id)):
>             for comment in self.LastJson['comments']:
>                 print(f"{comment['user']['username']} has posted a new comment: {comment['text']}")
> ```

can u look at this?
https://github.com/harrypython/itsagramlive/issues/4

**Comment by harrypython** [comment]
> can u look at this?
> #4

Sure, I forgot to close. Thank you 😄
