### ISSUE TITLE
2FA login problem

### ISSUE THREAD

**Issue by alitootia** [harrypython/itsagramlive#9]
Hi
When set 2FA in instagram. after enter code, get this message "Request return 500 error"

**Comment by alitootia** [comment]
> Hi
> When set 2FA in instagram. after enter code, get this message "Request return 500 error"

when using google authenticator don't have problem. when use sms have problem.

**Comment by harrypython** [comment]
@alitootia check the new version, let me know if works

**Comment by alitootia** [comment]
it is ture.
so thanks.
